spring:
    application:
        name: grpc.client
    grpc:
        client:
            channels:
                default:
                    address: 127.0.0.1:8080
                    negotiationType: PLAINTEXT

server:
    port: 8081
    error:
        include-message: always
        include-stacktrace: always

logging:
    level:
        com.grpc.client: INFO
        io.grpc: WARN
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
