spring:
    application:
        name: grpc.client
    grpc:
        client:
            channels:
                default:
                    address: 127.0.0.1:8080
                    negotiationType: PLAINTEXT

server:
    port: 8081
    error:
        include-message: always
        include-stacktrace: always
